### ISSUE TITLE
CodeMirror box on TextBox page is kinda broken

### ISSUE THREAD

**Issue by NotMyFault** [jenkinsci/design-library-plugin#103]
The cursor doesn't match the location you type in and every line is wrapped into `<pre>`:

https://user-images.githubusercontent.com/13383509/184684692-76b910ce-4fa4-4551-a779-fb3adcf441aa.mp4

For comparison, the script console:
![Screenshot 2022-08-15 at 19 25 29](https://user-images.githubusercontent.com/13383509/184684758-277a00b2-a191-430b-a9d5-06a9c13ad846.png)

**Comment by MondalSayantan** [comment]
Hi @NotMyFault,

I can work on this issue, but I am having some trouble in setting up the local development enviroment. On running the project on Gitpod and accessing the endpoint `/jenkins/design-library/` as written in the README, I am getting this error.

![image](https://user-images.githubusercontent.com/62999423/227861311-bfa646a5-ec14-452f-b755-246b6598613c.png)

**Comment by NotMyFault** [comment]
Maybe try to create a new workspace? I just created a gitpod workspace and it opened out of the box: https://8080-jenkinsci-designlibrary-qn4rqjz6mct.ws-eu92.gitpod.io/jenkins/design-library/

**Comment by MondalSayantan** [comment]
This issue seems to because of the `script` class
` <textarea class="script">println "Hello, World!"</textarea>`
in this file `src/main/resources/io/jenkins/plugins/designlibrary/TextBox/index.jelly`
I am having a hard time figuring out where definition for this class is located. Any help would be really appreciated. Thanks!
