### ISSUE TITLE
Show version on landing page

### ISSUE THREAD

**Issue by uhafner** [jenkinsci/design-library-plugin#362]
It would be helpful if the design library would show its release version somewhere on the landing page. 

When I navigate to https://weekly.ci.jenkins.io/design-library/ I cannot see if the changes that are shown in https://github.com/jenkinsci/design-library-plugin/releases/ are already deployed or not.

**Comment by SohamJuneja** [comment]
Hi @uhafner ,
I plan to update the index.jelly file to include a JavaScript fetch() API call that dynamically loads the plugin version and displays it on the homepage. The script will fetch data from GitHub's API and update the version element with the plugin version.
Let me know if you have any suggestions!

**Comment by uhafner** [comment]
I think it would be sufficient to show the plugin version using the Jenkins API. A connection to GitHub is not necessary.

**Comment by SohamJuneja** [comment]
@uhafner I’ve added a draft PR to display the plugin version on the Design Library landing page as suggested. However, I’m encountering an error during testing:
[ERROR] Failures:  
[ERROR]   InjectedTest.testPluginActive design-library failed to start  

I tried a few changes to resolve it, but the issue persists. Since I’m not very experienced with this, I wanted to share my progress. Please feel free to provide guidance on how to resolve the issue or let me know if I should step back from this task.

**Comment by uhafner** [comment]
The current error message in CI is:

Run 'mvn spotless:apply' to fix these violations.

It seems that your code is not correctly formatted.

**Comment by SohamJuneja** [comment]
I tried mvn spotless:apply earlier too sir and now have tried it once more but still the same error. Maybe there's something with the import statements , I'm using VS Code and it shows a red line below them but when I reload Java projects then the red line goes. After this I ran mvn spotless:apply , still it is giving the same error as I sent above.
