### ISSUE TITLE
CSS naming conventions

### ISSUE THREAD

**Issue by timja** [jenkinsci/design-library-plugin#58]
### Describe your use-case which is not covered by existing documentation.

What to name classes in plugins / core
What ! means in CSS classes

**Comment by timja** [comment]
@janfaracik possible to take a look at this?

**Comment by janfaracik** [comment]
Class names should follow [Block Element Modifier (BEM) methodology](http://getbem.com).

| Block                                            | Element                                                                                 | Modifier                                                                 |
|--------------------------------------------------|-----------------------------------------------------------------------------------------|--------------------------------------------------------------------------|
| Standalone entity that is meaningful on its own. | A part of a block that has no standalone meaning and is semantically tied to its block. | A flag on a block or element. Use them to change appearance or behavior. |
| e.g. header, container, menu, checkbox, input    | e.g. menu item, list item, checkbox caption, header title                               | e.g. disabled, selected, large                                           | 

A complete example could be `jenkins-cards__item--large` or `jenkins-button--disabled`.

---

Classes should be prefixed in a way that is unique to your service or plugin. We use prefixes due to the extensible nature of Jenkins, without prefixing we couldn't be certain a plugin class wouldn't interfere with a Jenkins class. We also use prefixing due to older libraries, such as Bootstrap, still being in use in Jenkins.

Jenkins will exclusively use the prefixes `jenkins-` and `app-` to namespace CSS classes, these prefixes should not be used in your plugins. A simple way to come up with a prefix for your classes is to use an acronym of your plugin name, e.g. `Jenkins Design Library` becomes `jdl`.

Classes prefixed with `jenkins-` indicate that they can be used in your plugin with confidence that they will only receive minimal changes, or they'll be indicated to have a major change in a new version of Jenkins.

Classes prefixed with `app-` indicate that they should not be used in your plugin as these classes are internal to Jenkins and may change at any time.

---

Not every class falls neatly into BEM, for example a class that does not belong to a particular component - such as a spacing or color class. For those classes we use the `-!-` convention created by GOV.UK to indicate that the classes can be used on any component.

A few examples: `jenkins-!-padding-6`, `jenkins-!-margin-6` and `jenkins-!-destructive-color`.

---------

How does that sound?

**Comment by daniel-beck** [comment]
It all makes sense now 🤯

**Comment by timja** [comment]
Sounds great thanks.

I would add some wording around legacy classes e.g. you say:
> Jenkins will exclusively use the prefixes jenkins- and app- to namespace CSS classes,

there's other classes that people need to use that aren't namespaced, shouldn't be worded so strongly.

> or they'll be indicated to have a major change in a new version of Jenkins

Not sure if I would word it that way. Jenkins doesn't follow semantic versioning.
You could probably just drop that sentence.

----

Best discussed on a PR anyway but the gist of it is great

**Comment by janfaracik** [comment]
Cheers everyone! I'll work on a branch/PR now to get this added
